### ISSUE TITLE
[Info needed] MQTT implementation azure-iot-device'.Client 

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-iot-sdk-node#105]
## Opening this on behalf of @Kapster17 as he initially opened this issue in azure-sdk-for-node https://github.com/Azure/azure-sdk-for-node/issues/2185

- Is there any documentation about the MQTT implementation for the 'azure-iot-device' Client
- How reliable is QoS=1 support for MQTT (How long does it buffer and retry ?). I have observed when there is internet connection loss. I DO NOT get any error for the Event Send call, and the Event is NOT delivered. What would be the best practice to ensure reliability ?
- Another query is how would be the best way to check if the connection is alive before I attempt client.open(connectCallback) again. On my Rp 3 in case of connection drops (I turn of my wifi), It takes more than 5 minutes to get a call back to client.on('disconnect', function (). I would need to have a open connection at all time. 
  - Would reopening the connection in client.on('disconnect', function () the correct way out ? This is assuming disconnect will always be called.

**Comment by pierreca** [comment]
Thanks @amarzavery !
@kapster17 not sure we've answered those in separate issues here or if they are still open for you - we've been doing a lot of work on the MQTT transport and there is more coming in the next few days including a full blown/customizable retry logic for the client.
In the next version the SDK will retry operations for you - with regards to detecting connection loss: in that case we're unfortunately bound by the limit of the OS (linux does not let us know that the connection drops and keeps the socket alive). we do implement a keepalive mechanism already and that's how we detect it but in order to save bandwidth it's set to ~3-4 minutes ping intervals. that explains the "more than 5 minutes" observation.

Regarding having the connection open all the time: yes you can reconnect on disconnect (at that point we know for sure the device is disconnected)

If you need to be connected at all times because you want to reestablish the connection and keep receiving cloud-to-device messages, the SDK will take care of that for you in the very near future (as much as it can, that is... if the hardware or connectivity is flaky, not much we can do about that except retry...).

**Comment by Kapster17** [comment]
Thanks Pierre.
When is the next version of the SDK expected ?
So what I do now is try is HTTP Request POST incase my mqtt call is taking time...while handling duplicates on the backend....works fine for now .....but would be ideal if the SDK took care of the same.

**Comment by pierreca** [comment]
Next version is expected within the next 2 weeks.

In any case your backend should handle duplicates. there are other points in the pipeline (other than the SDK) where messages could be retried and end up being duplicated. Good thinking!

**Comment by pierreca** [comment]
@Kapster17 the release is out:
- https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-10-24
- https://www.npmjs.com/package/azure-iot-device

Please let us know if this resolves (or at least improves) what you are seeing.

**Comment by Kapster17** [comment]
Pierre,
We tried the update for device (1.2.0)
What we observed is that for internet disconnect the behavior has become worse.
Earlier on a Linux system incase we unplugged our network connection .....the disconnected was fired in like 5-10 mins
After the new sdk we waited for like 15 mins with no disconnect being called.

I''l run a bunch of tests again and let you know.
PS:- we tried the sample code for the reconnects. But once we unplug the network we the custom function was not called.

**Comment by Kapster17** [comment]
Please reopen this issue.

**Comment by pierreca** [comment]
@Kapster17 
my guess is the disconnect was fired in 6 minutes tops, and now was bumped to 10. that's explainable (there's a 4 minutes timeout for retries after the disconnection has been detected and this takes at most 6 minutes due to the keepalive period).

Let's track this on a separate issue because even if the circumstances are the same for you, the code and the options we have to solve this are vastly different now. Also, I'm not sure what scenario you're trying to optimize for.

- making sure messages are sent and the SDK reconnects: that's a job for the newly shipped retry logic. we have parameters to tune this to your use case but this won't help detect disconnection. it will hide disconnections or make the timeout longer.
- detecting disconnection quickly: this is a job for the keepalive feature which is not configurable. for now. 

Please open a new issue, filling out as much as you can of the issue template. Please mention type of device, connectivity, your use case, what you would like to optimize for, and if there's behavior that you believe is a bug, code that exhibits it and logs showing what you observe. feel free to set the `DEBUG` environment variable to `*` to obtain even more logs of the issue.
