### ISSUE TITLE
Device Client - Retry Policy samples 

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-node#136]
Are there any samples of how to implement **Retry policies** for device client/twin?

I got it working and I'm happy to fork and submit a sample should it be of any help.

BTW... 
1. where are messages persisted while the client is disconnected? 
2. is there a policy setting for persistance such as where to persist and how much? 
3. are there any event handlers for _disconnected_ and _connected_?

Cheers

**Comment by pierreca** [comment]
Hi @wmmihaa 

a sample and a larger document about the retry policies is long overdue on our part but I haven't gotten to it yet, so if you'd like to submit a PR for one, sure, go for it. Simply for consistency reasons, I'd request that:
- it goes in the device/samples folder
- it sorta follows the same format as others (as simple as possible and straight to the point)

regarding your questions:
> 1. where are messages persisted while the client is disconnected?

in memory, there is no local storage, meaning those will be lost if the device reboots. Within the SDK there are different queues, and depending on what state the device is in (connected, not connected, link established, protocol used...) the exact queue might be different.

> 2. is there a policy setting for persistance such as where to persist and how much?

No, but I'd love to hear your thoughts and the settings you would like to see.

> 3. are there any event handlers for disconnected and connected?

Not yet but we do have a plan to introduce "connection status" events I want to be a little careful when introducing those because depending on the protocol and authentication method used they might not "mean" the same thing (for example, an MQTT connection is authenticated the moment it's connected, but not an AMQP one).

**Comment by pierreca** [comment]
> I'm thankful for the re-connect feature, but I thought it was unfortunate you built it so tight with re-submit. Loosing 4 minutes worth of data is not acceptable, so until that setting is configurable, I think we'll have to build it our self.

which feature? what are you losing? what are you calling "resubmit"? sending d2c messages? you shouldn't lose any there. 

> Using AMQP and NoRetry policy throws exceptions for un-delivered messages, however I don't know which messages failed :(. If I did, this would be where I'd persist them...

can you paste a console log and maybe a piece of code illustrating the problem? maybe some repro steps?

**Comment by wmmihaa** [comment]
> which feature? what are you losing? what are you calling "resubmit"? sending d2c messages? you shouldn't lose any there.

* I should not say re-connect feature, but rather fix: #28 
* Yes re-submittng/send d2c messages

> Q: where are messages persisted while the client is disconnected?
A: in memory, there is no local storage, meaning those will be lost if the device reboots. Within the SDK there are different queues, and depending on what state the device is in (connected, not connected, link established, protocol used...) the exact queue might be different.

Reading this again, realizing I misunderstood. I will only loos them on restart... sorry
