### ISSUE TITLE
Miss some informations from device twin

### ISSUE THREAD

**Issue by sukritch** [Azure/azure-iot-sdk-node#14]
I want to get the **connectionState** from the device twin feature (registry module). But I cannot get this property, responded from the sdk. Do I miss something?

My code:
`registry.getTwin('DEVICE_ID', function (err, twin) {
			if (err) {
				console.error(err);
			} else {
				console.log(twin);
			}
		});`

My sample response:
> {deviceId: 'DEVICE_ID',
  etag: 'ETAG',
  properties: 
   { desired: { '$metadata': [Object], '$version': 1 },
     reported: { '$metadata': [Object], '$version': 1 } },
  tags: {},
  _registry: 
   Registry {
     _config: 
      { host: 'HOST',
        sharedAccessSignature: [Object] },
     _restApiClient: RestApiClient { _config: [Object], _http: [Object] } } }

**Comment by pierreca** [comment]
The `connectionState` property doesn't exist on the device twin, it's directly in the device identity registry. So the API you want to use is the `Registry.get` method:
```js
registry.get('DEVICE_ID', function (err, dev) {
  if (err) { 
    console.error(err); 
  } else { 
    console.log(JSON.stringify(dev, null, 2); 
  } 
});
```

This being said, this `connectionState` property is useful mostly for debugging. Some light reading: 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#device-heartbeat

and especially in the table describing properties, here's what is said about `connectionState`:
>A field indicating connection status: either Connected or Disconnected. This field represents the IoT Hub view of the device connection status. Important: This field should be used only for development/debugging purposes. The connection state is updated only for devices using MQTT or AMQP. Also, it is based on protocol-level pings (MQTT pings, or AMQP pings), and it can have a maximum delay of only 5 minutes. For these reasons, there can be false positives, such as devices reported as connected but that are disconnected.

**Comment by pbatsii** [comment]
This doesn't seem to be entirely correct as of August 2018: 
IoT Hub -> Device Details -> Device Twin displays the connectionState property as part of the twin.
Simultaneously, retrieving Device Twin over API doesn't return this property along with some others, which seems to be a bit inconsistent.

**Comment by pierreca** [comment]
@pbatsii following feedback (such as this issue) we now replicate the `connectionState` property in the twin as well, and it's reflected in the latest versions of the SDK. which version of the SDK are you trying this with?

**Comment by pbatsii** [comment]
<PackageReference Include="Microsoft.Azure.Devices" Version="1.4.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.14" />
<PackageReference Include="Newtonsoft.Json" Version="9.0.*" />

This is C# Azure Function, Azure.Devices is 1.4.0 because I have run-time problems with 1.6.1:

-- if 1.6.1 is used with latest Newtonsoft.Json, then during run-time exception for Newtonsoft.Json 10.0.0.0 is thrown
-- if binding to Newtonsoft.Json 10.0.3 is added, the exception is thrown on line
var twin = await registryManager.GetTwinAsync(deviceId); --> Newtonsoft.Json complains about twin deserialization ..
-- if binding to Azure.Devices 1.4 and Newtonsoft.Json 11.0.1 or 10.0.3, serialized device twin has empty value elements .. 

So the only working combination right now is as above..

**Comment by pierreca** [comment]
@pbatsii I'm a bit lost now - The problem happens within an Azure Function, and with the C# SDK version 1.4.0?

The way the changes to the object model are rolled out at the REST API level is by introducing new "api-version" parameters in the HTTPS request. it's highly likely that the older SDK is using an older API version and that you need the new version of the C# SDK to use the latest api-version of the service - and if the problem is with a C# Function and SDK, there's not much we can do from here (this repo and issue are related to the Node.js SDK)

**Comment by pbatsii** [comment]
Thanks Pierre, understand the logic. This is indeed C# SDK -related; i just relalized its a Node.js repo .

**Comment by pierreca** [comment]
@pbatsii no problem at all. the C# repo is: https://github.com/azure/azure-iot-sdk-csharp

from the IoT Hub standpoint the best course of action is probably to update the SDK and then try to figure out why the runtime exception with the newtonsoft.json library happens
