### ISSUE TITLE
Supprt IoT Edge

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-node#168]
Hi, I am working on [Azure IoT Toolkit for VS Code](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit) (using Node SDK) to add IoT Edge support.

We want to add two features:
* List IoT Hub devices (and distinguish IoT Edge device)
* Create Edge device

For **List IoT Hub devices**, currently the `registry.list` api does not return the info to distinguish whether it is IoT Edge device or not, while the rest api (/devices/query) returns `capabilities.iotEdge` info but does not return the auth keys (symmetricKey). So if we want to get a device list with all the info, we need to have two API calls. Do we have plan to include IoT Edge info in `registry.list` api?

For **Create Edge device**, any plan to support to create an Edge device?

Thanks in advance!

**Comment by pierreca** [comment]
1. Create an edge device: right now you should be able to add the capabilities object to the device description and it should work, no SDK change needed (if you're using typescript we may have to update the Device interface - a pull request would be welcome)
2. List edge devices: right now you can do this with a query (`SELECT * from devices WHERE capabilities.iotEdge = true` I'm told) but to get the keys you'll have to call the get/list APIs separately - we are currently discussing the possibility to make this possible in a single API call but for now, since the service does not support this, the SDK doesn't either. The reason is that the SDK is trying to stay true to 1 method call == 1 API call. Since API calls might accrue to IoT Hub quotas/throttling limits, we don't want to mislead customers by running multiple API calls behind a single method call.

Please let us know if that helps!

**Comment by formulahendry** [comment]
Thanks @pierreca for the info. It is helpful!

**Comment by pierreca** [comment]
@formulahendry glad to hear that. is there anything else we can do or should we close the issue?

**Comment by formulahendry** [comment]
Hi @pierreca , Thank you! I think we could close this issue now.
