### ISSUE TITLE
IoT Hub publisher via redsocks and proxy drops connection

### ISSUE THREAD

**Issue by dushyantbangal** [Azure/azure-iot-sdk-node#18]
# Context
- **OS and version used:** Ubuntu 16.04
- **Node.js version:** 6.9
- **npm version:** 3.10

# Description of the issue:
I'm using `azure-iot-device-amqp`. I have a proxied connection so I'm using `redsocks` to reroute the connection via the proxy.

However, the proxy server sometimes drops the connection and starts again. But, the IoT hub publisher does not detect this. It keeps sending data and the IoT Hub does not receive anything. Nothing is shown on the IoT Hub subscriber as well.

I dont get the `Message Enqueued` message.

# Code sample exhibiting the issue:
[simple_sample_device.js](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js)

**Comment by pierreca** [comment]
It sounds like either Node.js or the amqp library doesn't detect that the connection drop. We've had issues with node sockets not emitting 'close' events on Linux so there's litterally  nothing we can do in those cases to detect the situation, unless rely on user-programmed timeouts (a simple setTimeout firing if no MessageEnqueued response was received for example). I'm not sure how redsocks influence this situation.

Out of curiosity, what's the end game when using redsocks? is it about punching through a firewall?

**Comment by dushyantbangal** [comment]
The client has an intel proxy, connections outside the network can only go through it.
We are using lots of other things besides `azure-iot` so we cannot go on handling proxy everywhere in our code.
Aim behind using redsocks is re-directing all connections from the system via the proxy.

**Comment by pierreca** [comment]
Allow me to rephrase just to see if I got that right: 
- you have a proxy on the network and must go through it. (Do you know what kind of proxy by the way?)
- you have multiple pieces of code with varying way to support proxy parameters
- in order to not have to handle the configuration of these pieces of code, you're relying on an infosec tool (redsocks) to redirect traffic to the aforementionned proxy

When doing that you see a few issues:
- the socket used by AMQP doesn't seem to disconnect the way it normally should
- MQTT has similar issues but when restarting redsocks it works (making me think restarting redsocks effectively kills the socket, and therefore reconnection is properly handled)

When you're saying "when the proxy drops the connection" are you talking about redsocks or the intel proxy on the network?

If your proxy is an HTTP proxy, have you tried using AMQP over Websockets or MQTT over websockets? How about using the HTTP transport itself, if you're not thinking about using twin features?

It feels like there are a lot of unknowns here that affect the behavior of the local socket. I'm not excluding a bug in the SDK, but it's hard to prove with that many layers. Especially:
- the proxy drops the connection
- restarting redsocks fixes the problem sometimes
- but you suspect that the SDK is responsible? 

Last but not least: we haven't designed any proxy support for now. it might work by chance, but it's not hasn't been a design goal yet. As much as I'm willing to help you, you're deep into uncharted territory here.

**Comment by dushyantbangal** [comment]
> When you're saying "when the proxy drops the connection" are you talking about redsocks or the intel proxy on the network?

intel proxy drops the connection.

>How about using the HTTP transport itself
We want to use a light weight protocol, that would be constantly maintaining the connection. I don't think HTTP would be ideal.

**Comment by dushyantbangal** [comment]
@pierreca this might be totally unrelated to proxy as well!

I started the "simulated device app" from [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted)
NOTE: I used AMQP here

After it is connected, I just removed my ethernet cable but it kept sending message.
The `disconnect` event was not detected.

After about 50-55 seconds, I reconnected my ethernet cable.
However, I still wasn't getting the "MessageEnqueued" status message in callback.

I keeps sending but nothing goes through!

**Comment by pierreca** [comment]
@dushyantbangal that might be a separate issue: we've spent some time tracking the behavior of "why no disconnect" when the network cable is unplugged, and haven't found a good way to detect it properly on Linux (it works fine on Windows). The reason is: node never fires the `disconnect` event on the underlying socket. 

In other words, relying on the socket `disconnect` event results in different behaviors depending on the OS and is not a surefire way of detecting network cable issues. We're going to invest more time in the next few weeks looking at other ways to do that but if you have suggestions they are more than welcome.

**Comment by dushyantbangal** [comment]
`aws-iot-device-sdk` lets you keep `keepAlive` as 0 and offline queuing. So it never checks for disconnection. With that, I can just keep on publishing and one the connection is up again, the messages get sent!

Hope you guy can find a similar fix

**Comment by pierreca** [comment]
It's a fair point, it's actually what our C SDK is doing, the Node SDK is lagging behind but this is all part of things we're looking to enable in the coming weeks. 
Dealing with connection status and resending messages is not trivial: disconnection must be differentiated from sending messages, since it may happen that a message could not be sent even though the connection can be established (throttling, quota exceeded, etc) and retrying to send the message in some cases can be detrimental, if at all possible - Also, there's the problem of caching the message locally and persistence (should the message queue persist over disconnection? over reboot? etc). 
Those are definitely things we're looking into, but our approach will have to be configurable and have acceptable defaults for a majority of customers.

This being said, if we're not providing an automated reconnect/retry mechanism we should provide ways to detect a bad situation - the thing we have works on windows for now, because the socket is closed when the OS detects that the connection has died, and Linux is different that way - so this is the first problem we need to address and that is what we're going to do in the coming days.

**Comment by jamesguitar3** [comment]
@pierreca I assume C# and other SDKs are also missing this automated reconnect/resume mechanism. Do you have a ETA for this? Thank you.

**Comment by pierreca** [comment]
@jamesguitar3 That question would be better asked on their respective github repos:
- https://github.com/azure/azure-iot-sdk-c
- https://github.com/azure/azure-iot-sdk-csharp

Both C and C# have some basic reconnection logic and queue mechanisms to retry sending messages after a connection is lost. The C# implementation has been in the works for some time now. I'm not sure what the state of things is for receiving messages and for device methods and twins.

ping @ewertons @jasmineymlo

**Comment by arkuhn** [comment]
@pierreca Has there been any decisions or updates on this issue since March? MQTT / Proxy / Linux support specifically with the Node SDK is of great interest to me. Thanks for your time.

**Comment by pierreca** [comment]
@arkuhn There are multiple issues discussed in here - if you have a specific scenario in mind I would encourage you to discuss it (with specifics) in a separate issue so that we can understand your needs clearly.

FYI, all transports (HTTP, AMQP and MQTT) have been greatly upgraded with much better state management since this discussion. this was the first step to enabling a full retry logic in the client itself, which is coming hopefully within the next 2 weeks (not this release, but the next).

Proxy support itself (over websockets I guess) is still unknown. 

Detecting disconnections on Linux will still be problematic since it doesn't depend on us. we would get better recovery if the connection recovers though, once we have this retry logic in place.

**Comment by pierreca** [comment]
Closing for lack of actionable follow up and the discussion has drifted, feel free to open a new issue if you encounter a new issue, especially after upgrading to the latest SDK packages in which the connection management has been improved.
