### ISSUE TITLE
Some questions about connection by x509

### ISSUE THREAD

**Issue by young-mu** [Azure/azure-iot-sdk-node#20]
In this [code file](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device_x509.js), it says we can establish the Azure IOT connection by providing a set of certificate and key. 

I have no idea about **where I can find the certificate and private key**, and **what is the relationship between them and Device Primary Key**. Thanks.

**Comment by pierreca** [comment]
The certificate and key files have to be generated by you, they are specific to one device.
The thumbprint for this certificate goes into the device registry instead of the device private key. In other words, for one specific device, you can either have a private key, or a certificate thumbprint, but not both.

A good example of code that creates a device with x509 and inserts it into the registry can be found here (
_Please note that you have to have openssl installed and configured for this script to work._):
https://github.com/Azure/azure-iot-sdk-node/blob/master/build/tools/create_device_certs.js


`iothub-explorer` can also handle creating the certificate and device for you:
https://github.com/Azure/iothub-explorer

```
$ iothub-explorer login <IOTHUB_CONNECTION_STRING>
$ iothub-explorer create <DEVICE_ID> --x509
```
.. and it will place the certificate and key files in the current directory, named after the deviceId you passed on the command line.

Please let us know if that solves your issue :)

**Comment by young-mu** [comment]
Ok, it works for me. Thanks very much !
