### ISSUE TITLE
Could not connect: UnauthorizedError: mqtt.js returned Connection refused: Not authorized error

### ISSUE THREAD

**Issue by arimk** [Azure/azure-iot-sdk-node#29]
Hi,

I am using a Node JS Azure function, with the SDK on top of it (I receive data from devices that cannot be sent directly to the IoT Hub, process it, send it back to the IoT hub and close the connection).
And I am having "Could not connect: UnauthorizedError: mqtt.js returned Connection refused: Not authorized error" error.
Worked yesterday up to 5 pm, then stopped now.
If I restart de function, it works again. Maybe I don't close the connection correctly (I do a `client.sendEvent(message, function(){ client.close(); }); ` ) ?

HostName=ecole-iot-hub.azure-devices.net
DeviceId=test_webhook

Seems the same as #21

**Comment by arimk** [comment]
Stopped again after an hour...

**Comment by arimk** [comment]
Switched to HTTP at the moment, better for my need.

**Comment by pierreca** [comment]
The fact that it disconnects after an hour looks more like a shared access signature renewal issue to me. can you paste the code used to create the client? how often are you sending messages?

**Comment by DanielSaager** [comment]
I've this error too. But I see no recognizable pattern. Sometimes it works for days, sometimes only for hours (not only one hour). The node.js script runs on raspi3 with a sometimes instable wlan connection. may be this is the cause...

**Comment by fshirzadi** [comment]
Anybody figured this out? Just had the same issue with MQTT. I have a device running node-red, connected to a laptop for wlan (shared internet). Turned off the laptop and now getting authorization error. Device has static IP and connects to the internet fine.

**Comment by pierreca** [comment]
@DanielSaager @fshirzadi @arimk 
apologies for the repeated issues. if you want us to look at the problem though, you need to give us a little something to work with. As you can see in my comment, I'm asking for code and maybe console logs. 
Another thing that could help diagnose the issue would be to set the `DEBUG` environment variable to "*".
Also, knowing which version of the SDK you're using could help. we're constantly improving reliability and the version number helps us narrow down the potential causes.

A little bit of background of what could be happening: MQTT uses shared access signature (Also referred to as SAS token) authentication, which has to be renewed on a regular basis. By default, a SAS token is created to be valid for 1 hour, and we have a timer mechanism that kicks in before that (at 45 minutes), and renews the SAS token. For the new SAS token to be used, the device has to be disconnected and reconnected. This mechanism works ONLY if you provide us with a connection string (using `Client.fromConnectionString()`. if you're using a Shared access signature directly (using `Client.fromSharedAccessSignature()` then we do not have the required information to renew the SAS token and it's on you to take care of that.

Things that could influence disconnection are:
- unstable connection (duh). That's why we're working on having an auto-reconnect/retry mechanism
- Azure load balancer closing the connection if it's inactive for more than 4 minutes (that's why we reconfigured the keep-alive ping mechanism in the last release)
- computer going to sleep and waking up: depending on the platform this might influence the socket lifecycle. 

When we hear about disconnection problems, we need to know about the exact circumstances of the error and how you create the client, how often you send messages, etc. Without this, the scope of potential errors is too wide and there's not much we can do (for now) to help you.

**Comment by DanielSaager** [comment]
we know are wifi connection is unstable. Then we changed the device internet connection to cable to everything works fine. so the retry mechanism is welcome :-)

**Comment by fshirzadi** [comment]
Device Explorer doesn't work either. Data monitor just hangs and sent messages expire. No error on device explorer side. It does update connection string and Add/Refresh device list fine. It was working fine before.

**Comment by pierreca** [comment]
@fshirzadi node-red can have weird caching issues of the connection string especially if you're copy/pasting nodes from one flow to another or if you have multiple nodes of the same type. that might be why it's using MQTT when you try AMQP. please use only 1 node or if you must use multiple node, do not copy-paste them.

**Comment by borisbstyle** [comment]
I have this same issue occassionally. Only way to solve it is to restart node-red

**Comment by jdiegogonzales** [comment]
Any news? I'm getting the same:
```
Could not connect: UnauthorizedError: mqtt.js returned Connection refused: Not authorized error
```
What should I share with you to fix this? I'm following the instructions under the [Get Started page for Node.js](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-getstarted) so my code uses the `Client.fromConnectionString()` piece.
