### ISSUE TITLE
Unable to uploadToBlob when using X509 device authentication

### ISSUE THREAD

**Issue by qimyi** [Azure/azure-iot-sdk-node#302]
As mentioned in the title, I could not get a file uploaded when I change the authentication method to X509. 
To test that the certs are OK, I've combined the 2 samples from this repo to show that I can make a connection to the IoT Hub and send messages but, upload failed with

```error uploading file: Error: Could not obtain blob shared access signature.```

Below code snippet used, with hostname and deviceId replaced.
```
'use strict';

const fs = require('fs');
const Protocol = require('azure-iot-device-mqtt').Mqtt;
const Client = require('azure-iot-device').Client;
const Message = require('azure-iot-device').Message;

const HOSTNAME = 'hostname';
const deviceId = 'myDevice';

const connectionString = `HostName=${HOSTNAME};DeviceId=${deviceId};x509=true`;
const certFile = `./devices/certs/${deviceId}.cert.pem`;
const keyFile = `./devices/private/${deviceId}.key.pem`;

const filePath = 'logs.txt';

const client = Client.fromConnectionString(connectionString, Protocol);

const connectCallback = function (err) {
  console.log('err', err); //eslint-disable-line
  if (err) {
    console.error('Could not connect: ' + err.message);
  } else {
    console.log('Client connected');
    client.on('message', function (msg) {
      console.log('Id: ' + msg.messageId + ' Body: ' + msg.data);
    });

    // Create a message and send it to the IoT Hub every second
    const sendInterval = setInterval(function () {
      const windSpeed = 10 + (Math.random() * 4); // range: [10, 14]
      const temperature = 20 + (Math.random() * 10); // range: [20, 30]
      const humidity = 60 + (Math.random() * 20); // range: [60, 80]
      const data = JSON.stringify({ deviceId: 'myFirstDevice', windSpeed: windSpeed, temperature: temperature, humidity: humidity });
      const message = new Message(data);
      message.properties.add('temperatureAlert', (temperature > 28) ? 'true' : 'false');
      console.log('Sending message: ' + message.getData());
      client.sendEvent(message, printResultFor('send'));
    }, 2000);

    client.on('error', function (err) {
      console.error(err.message);
    });

    client.on('disconnect', function () {
      clearInterval(sendInterval);
      client.removeAllListeners();
      client.open(connectCallback);
    });

    fs.stat(filePath, function (err, fileStats) {
      const fileStream = fs.createReadStream(filePath);
      console.log('filestats', fileStats.size); //eslint-disable-line

      client.uploadToBlob('testblob.txt', fileStream, fileStats.size, function (err, result) {
        if (err) {
          console.error('error uploading file: ' + err.constructor.name + ': ' + err.message);
        } else {
          console.log('Upload successful');
        }
      });
    });
  }
};


const options = {
  cert : fs.readFileSync(certFile, 'utf-8').toString(),
  key : fs.readFileSync(keyFile, 'utf-8').toString()
};

console.log('connection string', connectionString); //eslint-disable-line
console.log('setting options', options.passphrase); //eslint-disable-line


// Calling setOptions with the x509 certificate and key (and optionally, passphrase) will configure the client transport to use x509 when connecting to IoT Hub
client.setOptions(options);
console.log('options set'); //eslint-disable-line
client.open(connectCallback);
console.log('client.open'); //eslint-disable-line

// Helper function to print results in the console
function printResultFor(op) {
  return function printResult(err, res) {
    if (err) console.log(op + ' error: ' + err.toString());
    if (res) console.log(op + ' status: ' + res.constructor.name);
  };
}
```
Messages sent using client.sendEvent() are going through successfully 
```
send status: MessageEnqueued
```

**Comment by pierreca** [comment]
Hi, I just tried your code and it worked fine, I was able to upload to a blob. 

unfortunately we don't have a lot of debug statements in the file upload portion, so the easiest thing to figure out what's going on would be for you to set a breakpoint in the `node_modules/azure-iot-device/lib/blob_upload/file_upload_api.js` file and set a breakpoint line 38 to verify that the authentication provider returns the appropriate device credentials (ie verify that you actually have the cert and key properties there). if it doesn't it probably means there's something wrong that happens when reading the cert or key file. can you try that and report back?

**Comment by qimyi** [comment]
In the getBlobSharedAccessSignature() method:

```
else {
       x509Opts = deviceCredentials.x509;
}```

x509Opts is defined, with `cert` and `key` both defined with the pem file contents. 

The error was simply
`ERR Error: Unauthorized`

One thing though before I investigate any further, is the BlobStorage refusing to return a SAS URI because the root CA is a self-generated one?

**Comment by qimyi** [comment]
Thanks for your prompt replies!

The certificates are generated using instructions here
https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md
so they are not actually production type root CA certs. The root was uploaded to IoT Hub and verified, and they are still valid, as the messages are still getting enqueued, but the upload is not happening. 

device.cert.pem
```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----

```

device.key.pem
```
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
```

npm package versions
```
"azure-iot-device": "^1.4.3",
"azure-iot-device-mqtt": "^1.4.3",
"azure-iothub": "^1.3.2"
```

**Comment by pierreca** [comment]
interesting. would you mind testing with self-signed certificates (ie not signed with a CA cert)? I know it's less desirable but I'm trying to gauge what works and what doesn't on your setup - i'll try to set up a CA on my end to try your configuration as well.

**Comment by pierreca** [comment]
@qimyi 

I reproduced the issue and realized this is because of a current limitation of the Azure IoT Hub service: it does not support CA-signed cert authentication over HTTP (only AMQP or MQTT). That explains why you can still send messages but can't get SAS for blobs.

You have 2 options to make this work
1. change the authentication to self-signed certs or shared access signature
2. find another way to get or generate the SAS token for the blob on the device and use the azure-storage SDK directly - you can look at how we did that in `/device/core/src/blob_upload`.

please do let us know if this answers your question :)

**Comment by pierreca** [comment]
@qimyi closing after 8 days of inactivity, and since this is not a scenario supported by the service, there's not much we can do about it in the SDK

*thank you for your contribution to our open-sourced project! Please help us improve by filling out [this 2-minute customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).*
