### ISSUE TITLE
RetryOperation maxTimeout behavior

### ISSUE THREAD

**Issue by smanousos** [Azure/azure-iot-sdk-node#342]
azure-iot-common version 1.7.1, retry_operation.js line 37:

The maxTimeout behavior is described as "The maximum timeout for this operation, after which no retry will be attempted."  The actual calculation of totalRetryTime is the sum of all the retry intervals:
_this._totalRetryTime += nextRetryTimeout; 

This does not take into account the time it takes each iteration to fail. Which could be significant and cause retrying for much longer that maxTimeout.

Shouldn't the test to stop retrying be something like "(Date.now() - firstRetryTime) > maxTimeout ?

**Comment by pierreca** [comment]
sounds like what you're suggesting would work. 

The other debate we had in the team recently was whether we should take into account the time it took to fail between retries - knowing that for some i/o bound tasks it may not be possible to "cancel" them, leading to parallel operations in case of long timeouts/blocked calls. 

I'm marking this as "enhancement" since it's not broken, just incorrect, feel free to question/chime in/add details if this is a blocking issue and I'll upgrade this to a bug if that's the case.

**Comment by virtualamjath** [comment]
@pierreca can we change this MAX Timeout by keeping NoRetry () ?

**Comment by pierreca** [comment]
I believe this was fixed starting with version 1.10.0

**Comment by az-iot-builder-01** [comment]
@smanousos, @virtualamjath, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
