### ISSUE TITLE
Checking connection status in mqtt

### ISSUE THREAD

**Issue by Kapster17** [Azure/azure-iot-sdk-node#45]
We are using Raspberry PI 3 (Latest raspbian)and node to report sensor data to the azure iot hub. We need to run the device 24*7.
Few of main concerns
1- How reliable is QoS=1 support for MQTT (How long does it buffer and retry ?). I have observed when there is internet connection loss.  I DO NOT get any error for the Event Send call, and the Event is NOT delivered. 
2 - How do I check if the connection has been lost and need to re open. Currently we check for client.on('disconnect', function ()) and then call connect again. Is this best way to check if the connection is alive before I attempt client.open(connectCallback) again. My only concern is if I fail to get a call back on disconnect. I would never reconnect. Is there any other way to check connection status ?

I am caching the events and can resend in case of failures.

Thanks
Kaps

**Comment by pierreca** [comment]
Thanks for your question, a couple things:
1. the SDK automatically opens the connection if you call `sendEvent()`. So even without handling the `disconnect` event you should be fine as long as all you do is send. if you want to receive commands and messages, then you have to reopen the connection yourself.
2. For the SDK to reconnect properly it needs to authenticate the connection with an x509 certificate or a shared access signature. there are 2 ways to instantiate the client: `Client.fromConnectionString()` and `Client.fromSharedAccessSignature()`. If you're using `fromConnectionString()` there is a timer every 45 minutes that renews the shared access signature but forces a disconnection because the authentication data is sent with the connect frame. if you want long-lived connections with no disconnection, i'd suggest generating the Shared Access Signature yourself (so that you can set the expiryTime to whatever you want and disconnect/reconnect when you want) or use an x509 certificate.


One last thing: 
with the MQTT transport (and only with MQTT for now) there is a keepalive ping that, as its names implies, is supposed to keep the connection alive even when no events are sent. The reason we're slower at detecting a network failure with Linux compared to Windows is that Windows has a feature that detects the connection failure and terminates the sockets using that connection, whereas Linux doesn't do that: it keeps the socket opened. so the only way we detect the connection failure is by seeing that we never received a keepalive ping response, which ends up taking a few minutes. This is when the `disconnect` event will fire.

Does that answer your questions?

HTH
Pierre

**Comment by Kapster17** [comment]
Thanks Pierre....Appreciate you answering.
Few follows up questions
- Like you said sendEvent() will always try to connect ... but to receive commands and messages, then you have to reopen the connection yourself.
Is Disconnect the only way to check connection closure or is there any other property or event I need to listen to ?
-  I DO NOT get any error for the Event Send call, and the Event is NOT delivered. Please do confirm if this is a bug.
Steps to repro
1- Send Events....Call back for Send Event called.
2-Turn Off Internet
3- Call back for Send Event not called.

Thanks again.

**Comment by pierreca** [comment]
> Is Disconnect the only way to check connection closure or is there any other property or event I need to listen to ?

for now, it's the only way. we are working on improving the whole connection management system in the SDK but this is long-term work because we're working across 3 protocols (HTTP, AMQP and MQTT) and want to have the same high-level behavior.

> I DO NOT get any error for the Event Send call, and the Event is NOT delivered. Please do confirm if this is a bug.

Sounds like a bug - do you at least get the `disconnect` event? can you capture traces with the `DEBUG` environment variable set to `*` and post them (please remove authentication/sensitive logs if any).

Also i'd be curious to know if you see the same problem with AMQP

**Comment by Kapster17** [comment]
Sounds like a bug - do you at least get the disconnect event? can you capture traces with the DEBUG environment variable set to * and post them (please remove authentication/sensitive logs if any).
- Yes we do get a disconnect event. So right now we rely on that until we get a better connection management system in the future. Thanks.

**Comment by pierreca** [comment]
this is being addressed in #105 now I believe.
