### ISSUE TITLE
client.invokeDeviceMethod typescript signature

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-iot-sdk-node#459]
# Context
- **OS and version used:** Ubuntu 18.04
- **Node.js version:** 10.15.0
- **npm version:** 6.4.1

# Description of the issue:
The typescript signature for the client.invokeDeviceMethod for the Promise is not usable. The signature contains:
https://github.com/Azure/azure-iot-sdk-node/blob/978e014695481c2d770386d0996e004d3ab4e1e1/service/src/client.ts#L252-L254

Having this code in typescript

```
const result = await client.invokeDeviceMethod(deviceId, methodParams);
console.log(result.result);
```

results into a `Property 'result' does not exist on type 'void'.` Typescript uses the first signature with the optional `done?` and not the one with the Promise result.

**Comment by pierreca** [comment]
ping @kpajdzik 

we have 2 problems here:
1. Getting the compiler to recognize the promise option (which is what issue was filed for in the first place)
2. The result object itself (which is a consequence of the promisification of the SDK we just realized)

**1. Getting the compiler to recognize the promise option**
- could it be just an ordering problem with the overloaded function definitions?
- if not, would making the callback mandatory be breaking?

**2. The result object**
didn't realized that we introduced a wrapper object that contains both the result AND the HTTP response (which was there only for debugging purposes).

Sounds like now we're have the following options:
- Introduce a breaking change that returns the result but not the incoming message (may have to wait for v2. may have to fight for that)
- Same as before but we consider it's a bugfix not a breaking change (but it's breaking soo... not happy about this option from a semver perspective)
- we live with the current shape and update our samples to use the `result.result` field instead of the the returned object

**Comment by kpajdzik** [comment]
@pierreca 

I've synced with Tony last week.

1. I don't believe order matters here (except which overload is last and I believe ` invokeDeviceMethod(deviceId: string, moduleId: string, methodParams: DeviceMethodParams, done?: IncomingMessageCallback<any>): void;` should be last). I think that was one of the few calls where callback was optional before promisification. 

1. I was not aware that raw HTTP response is not needed. Flattening the response will make raw HTTP response impossible to access in Promise overload (not sure if anyone is using it) so I think the third option is the safest. The response shouldn't be treated as `Device` or `Twin` object but as a wrapper with `Device`/`Twin` and HTTP response inside.

**Comment by StefanSchoof** [comment]
I think the `invokeDeviceMethod(deviceId: string, moduleId: string, methodParams: DeviceMethodParams, done?: IncomingMessageCallback<any>): void;` is technically wrong. The implemented method will return a Promise is there are no callback. To have the signature for the implemented method the `?` had to removed: `invokeDeviceMethod(deviceId: string, moduleId: string, methodParams: DeviceMethodParams, done: IncomingMessageCallback<any>): void;`.

**Comment by pierreca** [comment]
@StefanSchoof I agree, the signature needs to be fixed. it doesn't make sense anyway for the callback to be optional here since by default methods will return a response. I'll submit a PR.

For the second part of the problem.. (which I believe is also addressed in a different issue) I think we'll live with it for now. we should've caught this in code review but it's now too late. it's not broken, just ugly, and changing it would be breaking.

**Comment by anthonyvercolano** [comment]
Published.

**Comment by az-iot-builder-01** [comment]
@StefanSchoof, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
