### ISSUE TITLE
Direct methods are not working

### ISSUE THREAD

**Issue by gauravagarwal28** [Azure/azure-iot-sdk-node#514]
I have uploaded all the relevant info here.

https://github.com/Azure/iotedge/issues/972

**Comment by anthonyvercolano** [comment]
Since you already have this issue open in the edge repo, I am going to close this.  If the edge folk feel that this is an SDK problem,  they will no doubt ask you to re-open this issue here.

In the meanwhile there is this doc https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#stability-issues-on-resource-constrained-devices and also comments near the bottom of issue #509

**Comment by az-iot-builder-01** [comment]
@gauravagarwal28, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
