### ISSUE TITLE
Export Iot Hub devices JSON to Blob Storage

### ISSUE THREAD

**Issue by Ilheu** [Azure/azure-iot-sdk-node#570]
Hi,
I'm trying to use my devices twins in Azure Stream Analytics, so I need to export the devices twins in a blob storage, so I can use as refrence input.
There is, this documentation about that https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-bulk-identity-mgmt, but it is in C#. Is there any example in javascript or nodejs ? Or can anyone help me how to do it ?

**Comment by pierreca** [comment]
@Ilheu your question talks about device twins but then points to an article that deal with exporting device identities. those two concepts are different.

If you want to export device identities to storage, we have an example here:
https://github.com/Azure-Samples/azure-iot-samples-node/blob/master/iot-hub/Samples/service/registry/registry_bulk_sample.js
this bulk export feature works for device identities but not device twins though.

If what you need to export is device twins, there is a most excellent article about how to deal with exporting device twins here:
https://azure.microsoft.com/en-us/blog/deep-dive-into-azure-iot-hub-notifications-and-device-twin/

because the twin notifications endpoint is also an event hubs-compatible endpoint you should also be able to hook this up directly to your ASA job, no storage involved.

unfortunately we don't have ready-made examples for this scenario but i hope these docs will give you something to start with. 

Thanks a lot for your question!

**Comment by pierreca** [comment]
closing after some inactivity, hoping we've answered the question. please let us know :)

**Comment by az-iot-builder-01** [comment]
@Ilheu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
