### ISSUE TITLE
Escalation issue 

### ISSUE THREAD

**Issue by mikevax** [Azure/azure-iot-sdk-node#591]
After network disconnect C2D call failed.

We have an issues with IoT/AMQP getting into a state where Cloud to device message delivers stops **after a network disconnect** and an IoT reconnect.. We are using the following node packages.

azure-iot-device-amqp@1.9.4
azure-iot-device@1.9.4
azure-iot-amqp-base@2.2.4
azure-iot-common@1.9.4

node version v8.12.0

Deployment Avigilon Blue Video surveillance cloud application.

The iot device manager shows the device connected, but all cloud to device request fail.

First we get an error:
,{"key":"deviceId","value":"01d27982-9834-4a89-bbc1-554cbf05f0c9"},{"key":"messageType","value":"notification"},{"key":"notificationType","value":"SLOW_HEARTBEAT"}]},"messageId":"d69b21d1-ab08-4015-acc6-69a30b627713","to":"","lockToken":"","userId":""} { Error: AMQP Transport: Could not send* 

Then we get an event from IOT in our notification que
2019-07-19 09:26:24 error: [iot-notificationQueue] fatal error processing notification. discarding. { ERROR: Fatal Disposition

Next we restart the connection, creating a new IoT connection.
from this point forward, we can send messages, but we can't receive messages. We restarted correctly.  I suspect that this is a Microsoft issue.

Note that resetting our node service correct the issue, however we prefer not to restart the service in order to ensure we do not miss security events. 

Any suggestions?

**Comment by mikevax** [comment]
Question:
 
   Are there any cloud to device throttling limits on a signal device.

**Comment by pierreca** [comment]
@mikevax i'm a little bit confused by all this information, so i'm going to copy/paste some of your text below and try to address or ask questions as best I can:

>We have an issues with IoT/AMQP getting into a state where Cloud to device message delivers stops after a network disconnect and an IoT reconnect

- You're talking about a device client correct? not a service client sending C2D messages?

If you're talking about a device client, I assume you mean that the device client gets disconnected. 
- Do you use the default retry policy that reconnects the client automatically, or do you alter this behavior or reconnect manually? 

>The iot device manager shows the device connected, but all cloud to device request fail.

- Which IoT Device manager are you referring to here? 
- What exactly tells you that the device is connected? Are you referring to a property of an object, to a message you receive, or something else?

> First we get an error:
,{"key":"deviceId","value":"01d27982-9834-4a89-bbc1-554cbf05f0c9"},{"key":"messageType","value":"notification"},{"key":"notificationType","value":"SLOW_HEARTBEAT"}]},"messageId":"d69b21d1-ab08-4015-acc6-69a30b627713","to":"","lockToken":"","userId":""} { Error: AMQP Transport: Could not send*

The very last part is cut off but looks like an client error. I'm not familiar with this JSON payload though, where is it coming from? is that your logger? Also, are you talking about a device client receiving C2D messages or a service client sending C2D messages?

> Then we get an event from IOT in our notification que
2019-07-19 09:26:24 error: [iot-notificationQueue] fatal error processing notification. discarding. { ERROR: Fatal Disposition

I'm not sure which notification queue you're talking about. can you elaborate?

> Next we restart the connection, creating a new IoT connection.
from this point forward, we can send messages, but we can't receive messages. We restarted correctly. I suspect that this is a Microsoft issue.

- How are you restarting the connection? 
- are you using the same client object, or a different one? 
- is that on the device side or on the service side?

> Note that resetting our node service correct the issue, however we prefer not to restart the service in order to ensure we do not miss security events.

I'm guessing this creates a whole new client object, which would basically restart and fix everything so that's not surprising, but I agree that you shouldn't have to do that... maybe you can shed some light by answering all the previous questions.

One thing i would also suggest to debug this is to set the DEBUG environment variable to either "*" or at least "azure*", it would greatly help us see what's going on.

> Are there any cloud to device throttling limits on a signal device.

Yes. See https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling

**Comment by smanousos** [comment]
@pierreca I can answer a couple of things for @mikevax
 
"**You're talking about a device client correct? not a service client sending C2D messages**?"
The device client disconnects because of a network failure.  It reconnects and is able to send D2C messages.  C2D messages are unable to reach the device however.

**"Do you use the default retry policy that reconnects the client automatically, or do you alter this behavior or reconnect manually"**
We use a modified version of your azureCommon.ExponentialBackOffWithJitter retry policy. Your unmodified policy does not take into account the time taken for each attempt to fail; only the sum of all retry intervals. We were seeing some very long failure detection times, consequently the retries would continue for too long.  We added a cut-off based on number of attempts.

**"Which IoT Device manager are you referring to here?
What exactly tells you that the device is connected? Are you referring to a property of an object, to a message you receive, or something else?"**
I believe Mike is referring to a Third Party tool called the "Device Explorer Twin". You give it a Iot Hub connection string and it provides all sorts of info about devices.

**"I'm not sure which notification queue you're talking about. can you elaborate?"**
This is an internal queue.  

**"How are you restarting the connection?
are you using the same client object, or a different one?
is that on the device side or on the service side?"**
We are creating a new instance of the client object.   At that point the client can send messages to the cloud.  The cloud is receiving them.  The cloud is unable to send messages to the device.  They get queued up.

**Comment by pierreca** [comment]
@smanousos thanks, this clarifies a few things. more context below:

> "Do you use the default retry policy that reconnects the client automatically, or do you alter this behavior or reconnect manually"
We use a modified version of your azureCommon.ExponentialBackOffWithJitter retry policy. Your unmodified policy does not take into account the time taken for each attempt to fail; only the sum of all retry intervals. We were seeing some very long failure detection times, consequently the retries would continue for too long. We added a cut-off based on number of attempts.

FYI we fixed this max timeout calculation problem a few weeks ago: https://github.com/Azure/azure-iot-sdk-node/commit/026fa2bcef51f5ae8f8a000fa4cb42038bdf089c

> "Which IoT Device manager are you referring to here?
What exactly tells you that the device is connected? Are you referring to a property of an object, to a message you receive, or something else?"
I believe Mike is referring to a Third Party tool called the "Device Explorer Twin". You give it a Iot Hub connection string and it provides all sorts of info about devices.

I'm not familiar with this device explorer but there are known limitations around using the `ConnectionState` property on the `Device` object property on the service sdk side that may indicate wrong if the device connection is in the process on timing out. I wouldn't trust this property as a source of truth for what's happening in case of timeouts of flaky connections.

> "How are you restarting the connection?
are you using the same client object, or a different one?
is that on the device side or on the service side?"
We are creating a new instance of the client object. At that point the client can send messages to the cloud. The cloud is receiving them. The cloud is unable to send messages to the device. They get queued up.

That scares me. a new client object will create a whole new connection, and subscribe to the c2d messages topic (or links in the case of AMQP) again, so C2D messages that weren't previously delivered should be at that point. if you were reusing the client, we could suspect a bug in the state management of the SDK, but if you're recreating a totally new client and reconnecting it, it may have to do with the service itself.

When you create a new client, is the old one destroyed and disconnected at that point? or is it still held in memory somewhere? I wonder if there could be a race between these clients.

**Comment by smanousos** [comment]
@pierreca Sorry, I thought I responded to this.  We are calling .removeAllListeners() then .close() on the client.  After that we create a new instance.

**Comment by mikevax** [comment]
pierreca, Hi, we need to prepare a hot fix for this issue ASAP, having major customer impact, I noticed this fix, could it be related ?
AMQP Transport: Unexpected exception being thrown when connectivity is unstable. #569
https://github.com/Azure/azure-iot-sdk-node/issues/569

note we are on version 1.9.4, prior release was 1.7.1. What version would you recommend for the best connection stability and reliability.

**Comment by mikevax** [comment]
Any update ? note we are on version 1.9.4, prior release was 1.7.1. What version would you recommend for the best connection stability and reliability. We need to know whether we should backout version version 1.9.4 and go back to version 1.7.1.

**Comment by YoDaMa** [comment]
@mikevax we recommend the latest release, since it will have the most current bugfixes. That would be azure-iot-device-amqp@1.10.1.

**Comment by pierreca** [comment]
@mikevax aside from @YoDaMa's recommendation which is correct, i'll try to summarize what i understand:
1. the device client is disconnected then reconnected after network issues. this should re-enable C2D reception. If we have a bug there I believe that's a code path where we added a lot of logs in one of the latest versions so having full debug logs on the device side might be interesting. to enable full debug logs, just set the DEBUG environment variable to "*". What I'm really looking for is if the reconnection and attaching the c2d links is successful after the network loss. 

2. on a closer read it seems as though there is also a node service client involved to send the C2D message and that's where you're seeing the "AMQP Transport" Could not send" error. correct? if that's the case, then the problem might not be on the device side. @smanousos you're saying about C2D messages "the cloud is receiving them, they are getting queued up". if you get an AMQP Transport error, it's unlikely that this operation would be successful. So I wonder if we're chasing multiple things at a time.

@mikevax @smanousos is there any way for you to obtain debug logs either on the device or service side, or even better on both?

**Comment by mikevax** [comment]
I see about getting you the latest logs. IS there a schedule to when the next LTS branch will be posted. The last one was almost a year ago.

**Comment by mikevax** [comment]
Is release_2019-8-26 the one we should be using in out next release ? Also when is the next LTS release scheduled ?

**Comment by pierreca** [comment]
@mikevax we're trying to fix a few bugs and get the github issue count down a bit before we release an LTS. it will be based on the version from `release_2019-8-26`, yes.

**Comment by YoDaMa** [comment]
Hi @mikevax, taking this issue over from @pierreca. We have released `lts_09_2019`, which has been tagged as such in npm. That should be used in your release.

**Comment by az-iot-builder-01** [comment]
@mikevax, @smanousos, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
