### ISSUE TITLE
Status Code: 400 Bad Request iothub-errorcode: InvalidProtocolVersion

### ISSUE THREAD

**Issue by Boyka1290** [Azure/azure-iot-sdk-node#617]
![2019-09-05_1656](https://user-images.githubusercontent.com/54944738/64345868-b7021f80-d00e-11e9-9a19-d60f00ff40d3.png)

**Comment by anthonyvercolano** [comment]
@Boyka1290 Thank you for the problem report.

I really have zero context for what you've filed here.  When filing an issue a bit more information is requested.  This was asked when you filed.  I will repeat here:

# Context
- **OS and version used:** <VERSION> 
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 

# Description of the issue:


# Code sample exhibiting the issue:


# Console log of the issue:

**Comment by pierreca** [comment]
@Boyka1290 
highly likely related to a missing api-version query parameter.
this is how we insert it in the node SDK: https://github.com/Azure/azure-iot-sdk-node/blob/master/common/core/src/endpoint.ts#L66

try adding `?api-version=2019-03-30` to your query URL.

Closing since:
1. I believe this is the answer
2. this seems unrelated to the node client library anyway, it's a generic question about Azure IoT Hub, which would probably belong on the forums or stack overflow than here. no indication that this is related to the code in this repository.

**Comment by az-iot-builder-01** [comment]
@Boyka1290, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
