### ISSUE TITLE
error TS7016: Could not find a declaration file for module 'amqp10'

### ISSUE THREAD

**Issue by jenscl** [Azure/azure-iot-sdk-node#67]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v6.10.1
- **npm version:** 5.3.0

# Description of the issue:

I'm using the Azure IoT service SDK with TypeScript. The message below appears when compiling the TypeScript code. The `@types/amqp10` package does not exist and adding a custom declaration file with just `declare module 'amqp10';` generates a different error. How can I solve this? It would be great if the right declaration files were installed with the azure-iothub package.

# Console log of the issue:

```
<path>/node_modules/azure-iot-amqp-base/lib/amqp_receiver.d.ts(4,52): error TS7016: Could not find a declaration file for module 'amqp10'. '<path>/node_modules/azure-iot-amqp-base/node_modules/amqp10/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/amqp10` if it exists or add a new declaration (.d.ts) file containing `declare module 'amqp10';`
```

Thanks in advance!

**Comment by pierreca** [comment]
The method suggested by npm won't work because the typings for amqp10 are not up to date.

The `amqp10` is a dependency that is not maintained by us and their typings still used the old `typings` utility: they can be installed with `typings install amqp10`. 

I don't think there's anything "clean" we can do with our packages to get those installed. We could define a postinstall step that runs `typings install` but that would burden the vast majority of our customers using only javascript with unnecessary files.
