### ISSUE TITLE
Multiple handler functions for same Device Twin desired path causes additional calls to handler functions

### ISSUE THREAD

**Issue by stenbergd** [Azure/azure-iot-sdk-node#875]
# Context

- **OS and version used:** Ubuntu 18.04
- **Node.js version:** v10.22.0
- **npm version:** 6.14.7
- **list of installed packages:** azure-iot-device@1.17.0, azure-iot-device-amqp@1.13.0

## Description of the issue

Multiple handler functions for same device twin desired path causes additional calls to handler functions. This arises from me wanting to have smaller functions (each dedicated to specific tasks) act independently on the same device twin path update event. In the printout below, I was expecting only one of each printout, i.e.

```
Function 1
Function 2
```
not

```
Function 1
Function 2
Function 1
Function 2
```

## Code sample exhibiting the issue

```
var Client = require('azure-iot-device').Client;
var Protocol = require('azure-iot-device-amqp').Amqp;

var deviceConnectionString = 'INSERT_DEVICE_STRING_HERE';

var client = Client.fromConnectionString(deviceConnectionString, Protocol);

client.open(function(err) {
  if (err) {
    console.error(err);
  }  else {
    client.getTwin(function(err, twin) {
      if (err) {
        console.error(err);
      } else {
        twin.on('properties.desired', function(delta) {
            console.log('Function 1');
        });

        twin.on('properties.desired', function(delta) {
            console.log('Function 2');
        });
      }
    });
  }
});
```

## Console log of the issue

```
Function 1
Function 2
Function 1
Function 2
```

**Comment by az-iot-builder-01** [comment]
@stenbergd, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by anthonyvercolano** [comment]
This is really a by design.

It very much has to do with how node handles events.

You're doing two on's right in a row.  The action of the on will happen right away.  The emit's won't happen until the next tick.  So both your event handlers will be set up right away.  The emit caused by the first one will fire and cause both callbacks to be invoked.  Then the emit for the second one will occur which since both event handlers were still both set up will both callbacks to be invoked.

Note that if you then actually change something in the desired part of the twin you will simply get:

Function 1
Function 2.

**Comment by stenbergd** [comment]
Alright, I think I understand the background of this and accept your answer. Only in my case I thought it was a bit of a strange behavior, but I guess multiple subscribers of the same DT path is not the recommended use. Just thought I might test this question in Github issue court :)

I'll think about how to implement appropriate abstractions to handle this scenario in my code.

Thanks
/Daniel
